---
- name: Install latest Apache Web server and make sure it is running
  hosts: node1
  tasks:
    - name: Install latest Apache
      yum:
        name: httpd
        state: latest
    - name: Start Apache service
      service:
        name: httpd
        state: started
    - name: Setup home page
      copy:
        src: index.html
        dest: /var/www/html
        mode: 0644
    - name: Install firewalld
      yum:
        name: firewalld
        state: latest
    - name: Install firewall pip module
      pip:
        name: firewall
    - name: Setup http port
      firewalld:
        service: http
        permanent: yes
        state: enabled

